sudo: required

service:
  - docker 
  
before_install:
  - docker pull ezware/openrbuild
  - docker images 
  - docker run -it --name openr123 ezware/openrbuild  /bin/bash 
  - docker ps -a

#before_script:
  

#script:
  
