
language: go

sudo: required

service:
  - docker 
  
before_install:
  - docker pull ezware/openrbuild
  - docker images 
  - docker run -itd --name openr123 ezware/openrbuild  /bin/bash 
  - docker ps -a
  - docker ps

#before_script:
  

#script:
  
